### PR TITLE
Face Emotion Detection, Pose Estimation and Red Dots on Green

### PR DESCRIPTION
**Pull request by Alok5445Sagar**
I have added the codes for 3 project.
First: We can detect emotions of face of a person in the live video or any input MP4 video.
Second: Pose of person can be estimated in the live video or input video.
Third: This code detect every red dots in an input video and show green dots over them

The video input and output is also shared in each folder

### CODE REVIEW

**Comment by py3-coder** [comment]
Hey @Alok5445Sagar  .
Need to add all these project in CONTRIBUTION.md

**Comment by Alok5445Sagar** [comment]
Okay sure!

**Comment by Alok5445Sagar** [comment]
Hey! I have created another pull request after adding my project in contribution.md file. Please merge my prs

**Comment by Alok5445Sagar** [comment]
Done!!
Have a look

**Comment by py3-coder** [comment]
PR accepted @Alok5445Sagar 
Successfully merged to CART repo.
Need to Star this repo incase not done.
🚀🚀👍

**Pull request merged**
