### PR TITLE
Twitter Sentiment Analysis_NLP

### PR DESCRIPTION
**Pull request by aditi072**
Successfully added Twitter sentiment analysis, please have a review and merge my PR.

### CODE REVIEW

**Comment by aditi072** [comment]
Please add hacktoberfest-accepted tag to make my PR count towards hacktoberfest.

**Comment by py3-coder** [comment]
Hey @aditi072  , add the project data in CONTRIBUTION.md .
Read this [CONTRIBUTION.md](https://github.com/py3-coder/Model-EDA-Analysis-CART/blob/main/CONTRIBUTION.md)
PR accept @aditi072 
Need to Star this repo incase not done.
Just Update the required will merge to main
🚀🚀👍

**Comment by aditi072** [comment]
done

**Comment by py3-coder** [comment]
Make sure do changes in same PR form next time.
@aditi072

**Pull request merged**
